### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by Chocohead** [user11681/phormat#1]
Might just be me misreading the vanilla code flow, but [`TextRendererDrawerMixin#formatCustom`](https://github.com/user11681/phormat/blob/1.16/src/main/java/user11681/phormat/asm/mixin/TextRendererDrawerMixin.java#L90) looks to be capturing things in the wrong order. I think it's misgrabbing the alpha as red, then everything else is shifted as a result:

```java
FontStorage lv = TextRenderer.this.getFontStorage(arg.getFont());
Glyph lv1 = lv.getGlyph(j);
GlyphRenderer lv2 = arg.isObfuscated() && j != 32 ? lv.getObfuscatedGlyphRenderer(lv1) : lv.getGlyphRenderer(j);
boolean flag = arg.isBold();
float f = this.alpha; //This is the first float the Mixin captures, you have it as red
float f1, f2, f3; {
	TextColor lv3 = arg.getColor(); 

	if (lv3 != null) {
		int k = lv3.getRgb();
		f1 = (float)(k >> 16 & 255) / 255.0F * this.brightnessMultiplier;
		f2 = (float)(k >> 8 & 255) / 255.0F * this.brightnessMultiplier;
		f3 = (float)(k & 255) / 255.0F * this.brightnessMultiplier;
	} else {
		f1 = this.red;
		f2 = this.green;
		f3 = this.blue;
	}
}

if (!(lv2 instanceof EmptyGlyphRenderer)) {
	float f7 = flag ? lv1.getBoldOffset() : 0.0F;
	float f8 = this.shadow ? lv1.getShadowOffset() : 0.0F;
	VertexConsumer lv4 = this.vertexConsumers.getBuffer(lv2.method_24045(this.seeThrough));
	TextRenderer.this.drawGlyph(lv2, flag, arg.isItalic(), f7, this.x + f8, this.y + f8, this.matrix, lv4, f1, f2, f3, f, this.light);
}

float f9 = lv1.getAdvance(flag); //This is captured as alpha
float f10 = this.shadow ? 1.0F : 0.0F; //This is captured as advance
if (arg.isStrikethrough()) {
	addRectangle(new GlyphRenderer.Rectangle(this.x + f10 - 1.0F, this.y + f10 + 4.5F, this.x + f10 + f9, this.y + f10 + 4.5F - 1.0F, 0.01F, f1, f2, f3, f));
}

if (arg.isUnderlined()) {
	addRectangle(new GlyphRenderer.Rectangle(this.x + f10 - 1.0F, this.y + f10 + 9.0F, this.x + f10 + f9, this.y + f10 + 9.0F - 1.0F, 0.01F, f1, f2, f3, f));
}

this.x += f9; //Mixin injects at this point
return true;
```

I couldn't see any usages of `Phormatter#format` to be certain for sure, so I might be wrong.

On a related note, isn't the [ASM for `TextColorMixin`](https://github.com/user11681/phormat/blob/1.16/src/main/java/user11681/phormat/asm/PhormatMixinConfigPlugin.java#L67-L98) the equivalent of a cancelling head inject? Didn't see a reason for it to be ASM, not that there's necessarily anything wrong with it, but thought I'd ask if there was a special need for it not to be a Mixin. The block above also looks like a `@Redirect` with multiple targets which I think you could do directly as a Mixin as well.

**Comment by user11681** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;According to Mixin, alpha (`f`) comes before red (`m`):
```
/*   [  8]                 float  m                                                  <capture>
/*   [  9]                 float  n                                                  <capture>
/*   [ 10]                 float  o                                                  <capture>
/*   [ 11]                 float  f                                                  <capture>
```
—although source and bytecode show otherwise—and a breakpoint on the yellow splash text appears to confirm it (unless I don't understand colors anymore; `red = 1`, `green = 1`, `blue = 0` and `alpha = 1`).
&nbsp;&nbsp;&nbsp;&nbsp;Indeed, the `getRgb` injection is equivalent to conditionally canceling at the head, but the target is available only on the client and annotating it with `@Environment(EnvType.CLIENT)` strips the method from the server only in development environments, causing dedicated servers to crash in production environments. I could have made a client-only mixin and a duck interface for the main mixin's fields or used ASM directly; of course, I chose the latter.
&nbsp;&nbsp;&nbsp;&nbsp;The multiple-target redirect above exists because—if my memory serves—Mixin seemed to be unable to locate the `ordinal` invocation in the varargs method, and since the modification is the same for all of the 3 methods, I did it with ASM.

**Comment by Chocohead** [comment]
Most odd, but much of Mixin's local capture is in that sense. Ironically it's one of the few things OptiFine actually improves as recompiling flattens the locals out to follow the source more closely (at the expense of mods expecting it to be how Mojang actually did it of course).

I think you can extend mixins from other mixins to use fields which one may add... but equally I suppose that's just exchanging one uncommon workaround for another. I expect the ordinal problems stem from Mixin's remapping being limited shall we say too, it's not really designed for the classes to change when the method/field it's trying to remap doesn't. It's often much harder to work around when it's being stubborn (without abandoning using the Mixin in favour of something else) so I guess it's all a case of being what it is.
